server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:~/local
    username: root
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    output:
      ansi:
        enabled: always

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
custom:
  site:
    baseUrl: http://localhost:8080