spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: b1905c669b33bde6ff3798db8f1ed250

custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: oauthId
              nickname: nickname
  fileDirPath: /Users/nia/Documents/work/